### ISSUE TITLE
Many cplex tests failing with Cplex' has no attribute 'solution' (cplex 12.7.1)

### ISSUE THREAD

**Issue by matthiaskoenig** [biosustain/optlang#102] opened 2017-04-07 16:35 UTC
When running the nosetests locally many cplex tests fail with cplex 12.7.1.
This is not caught by the continuous integration because this tests are skipped on travis and appveyor.

```
======================================================================
14) ERROR: test_netlib_check_objective_value_25FV47 (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
15) ERROR: test_netlib_check_objective_value_80BAU3B (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
16) ERROR: test_netlib_check_objective_value_ADLITTLE (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
17) ERROR: test_netlib_check_objective_value_AFIRO (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
18) ERROR: test_netlib_check_objective_value_AGG2 (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
19) ERROR: test_netlib_check_objective_value_AGG3 (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
20) ERROR: test_netlib_check_objective_value_BANDM (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    optlang/tests/test_netlib_cplex_interface.py line 60 in check_objval
      if problem.solution.get_status() == cplex.Cplex.solution.status.optimal:
   AttributeError: type object 'Cplex' has no attribute 'solution'
======================================================================
21) ERROR: test_netlib_check_objective_value_BEACONFD (test_netlib_cplex_interface.pyc)
----------------------------------------------------------------------
...
```

**Comment by cdiener** [comment] 2017-04-07 21:27
Looks like a duplicate of your own #95...

**Comment by matthiaskoenig** [comment] 2017-04-07 23:58
Yes, I think it is the same issue but in different place in the code base. 
This one is not urgent, I just noticed it when trying to run the tests.

**Comment by KristianJensen** [comment] 2017-04-08 08:16
Thanks for the heads up. Should be fixed now.

**Closed by KristianJensen** 2017-04-08 08:16 UTC
