### ISSUE TITLE
optlang/GLPK determinism is broken

### ISSUE THREAD

**Issue by schanzel** [biosustain/optlang#14] opened 2016-05-05 10:48 UTC
There seems to be an issue regarding the order of rows/cols provided for GLPK.

Running the exakt same input twice, GLPK guarantees to give the exact same output. This applies to the objective value as well as the variable values. 

Anyway, feeding optlang/GLPK with the exact same data twice does in fact result in the same objective value, but the variable values differ over runs if there is more than one combination of variable values leading to an optimal objective value.

See [this gist](https://gist.github.com/schanzel/6e95a9a08308c44193d9b4fb04fd6732) as an example binary problem where any combination of '1's in a matrix (subject to any row's sum being <= 1) leads to an optimal solution. Running this sample code several times shows how the result matrix differs.

I think, regarding determinism, optlang should provide the same output given the same input across runs.
Any thoughts on this?

**Comment by KristianJensen** [comment] 2016-05-05 11:41
Hi Benjamin

Thanks for your report. You are right that GLPK is deterministic in the sense that repeated solving of the same problem will give identical solutions, even if several optimal points exist.

The non-deterministic behaviour you described is caused by variables being added in a different order on repeated executions. The issue can be easily circumvented however by explicitly adding the variables to the problem before adding the constraints or setting the objective ("model.add(vars_list)"), which will ensure that the variable ordering remains the same. For larger problems adding the variables explicitly can also be quite a bit faster than letting them be added implicitly.

Regardless, even implicit addition of variables should be deterministic. I will look into why this is not the case.

Best regards,
Kristian

**Comment by schanzel** [comment] 2016-05-05 12:09
Hi Kristian,

thanks for the advice! Adding the variables first actually solves my issue with this for now. 👍 

Best,
Benjamin

**Comment by KristianJensen** [comment] 2016-06-13 08:14
I've pushed a fix that makes this behave deterministically (variables that are added implicitly will be added in alphabetical order by their name). Thanks again, if you have any other bug reports, comments or suggestions don't hesitate to let us know.

**Closed by KristianJensen** 2016-06-13 08:14 UTC
